### ISSUE TITLE
Select Account Type Spinner not working properly [GCI]

### ISSUE THREAD

**Issue by harshshinde07** [openMF/self-service-app#1230]
**Summary:**

For every failed request, the spinner duplicates all the list items. The task here is to prevent this behavior. 

**Screenshots:**

<img src="https://user-images.githubusercontent.com/25999879/69901618-27b89e00-13aa-11ea-854f-12a5f346f119.png" width=200 />

**Comment by harshshinde07** [comment]
@santoshconflux Please add the GCI tag.

**Comment by OHassini** [comment]
Hi, I just fixed this issue please have a look at my PR 😄

**Comment by vibhusharma101** [comment]
Can I work on this issue?
@devansh-299 this issue still exists in the app

**Comment by harshshinde07** [comment]
@vibhusharma101 the PR is yet to be merged that's why the issue still exists in the app. Once it is done it will be fixed.

**Comment by vibhusharma101** [comment]
Okay @harshshinde07

**Comment by luckyman20** [comment]
Issue does not exist anymore.
